{application,rt53,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {modules,[rt53,rt53_app,rt53_auth,rt53_req,rt53_server,
                        rt53_sup]},
              {applications,[kernel,stdlib]},
              {mod,{rt53_app,[]}},
              {env,[]}]}.
